spring:
  application:
    name: lyrassist
  mvc:
    problemdetails:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/lyrassist
    username: lyrassist
    password: lyrassist
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
